Exception on /reset_password_request [POST]
Traceback (most recent call last):
  File "d:\python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Python27\microblog\app\routes.py", line 144, in reset_password_request
    send_password_reset_email(user)
NameError: global name 'send_password_reset_email' is not defined
Microblog startup
Exception on /reset_password_request [POST]
Traceback (most recent call last):
  File "d:\python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Python27\microblog\app\routes.py", line 144, in reset_password_request
    send_password_reset_email(user)
  File "D:\Python27\microblog\app\email.py", line 18, in send_password_reset_email
    user=user,token=token))
  File "D:\Python27\microblog\app\email.py", line 9, in send_email
    mail.send(msg)
  File "d:\python27\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "d:\python27\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "d:\python27\lib\smtplib.py", line 773, in quit
    res = self.docmd("quit")
  File "d:\python27\lib\smtplib.py", line 394, in docmd
    self.putcmd(cmd, args)
  File "d:\python27\lib\smtplib.py", line 342, in putcmd
    self.send(str)
  File "d:\python27\lib\smtplib.py", line 334, in send
    raise SMTPServerDisconnected('please run connect() first')
SMTPServerDisconnected: please run connect() first
Microblog startup
Exception on /reset_password_request [POST]
Traceback (most recent call last):
  File "d:\python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Python27\microblog\app\routes.py", line 163, in reset_password_request
    send_password_reset_email(user)
  File "D:\Python27\microblog\app\email.py", line 18, in send_password_reset_email
    user=user,token=token))
  File "D:\Python27\microblog\app\email.py", line 9, in send_email
    mail.send(msg)
  File "d:\python27\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "d:\python27\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "d:\python27\lib\smtplib.py", line 773, in quit
    res = self.docmd("quit")
  File "d:\python27\lib\smtplib.py", line 394, in docmd
    self.putcmd(cmd, args)
  File "d:\python27\lib\smtplib.py", line 342, in putcmd
    self.send(str)
  File "d:\python27\lib\smtplib.py", line 334, in send
    raise SMTPServerDisconnected('please run connect() first')
SMTPServerDisconnected: please run connect() first
Microblog startup
Microblog startup
Microblog startup
Exception on / [GET]
Traceback (most recent call last):
  File "d:\python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python27\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "D:\Python27\microblog\app\routes.py", line 36, in index
    posts=posts.items,next_url=next_url,prev_url=prev_url)
  File "d:\python27\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "d:\python27\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "d:\python27\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Python27\microblog\app\templates\base.html", line 43, in top-level template code
    {% if current_user.is_anonymous %}
  File "d:\python27\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\python27\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "d:\python27\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "d:\python27\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\Python27\microblog\app\templates\base.html", line 63, in block "content"
    {% block app_content %}{% endblock %}
  File "D:\Python27\microblog\app\templates\index.html", line 5, in block "app_content"
    {{wtf.quick_form(form)}}
  File "d:\python27\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'wtf' is undefined
Exception on /index [GET]
Traceback (most recent call last):
  File "d:\python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python27\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "D:\Python27\microblog\app\routes.py", line 36, in index
    posts=posts.items,next_url=next_url,prev_url=prev_url)
  File "d:\python27\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "d:\python27\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "d:\python27\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Python27\microblog\app\templates\base.html", line 43, in top-level template code
    {% if current_user.is_anonymous %}
  File "d:\python27\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\python27\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "d:\python27\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "d:\python27\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\Python27\microblog\app\templates\base.html", line 63, in block "content"
    {% block app_content %}{% endblock %}
  File "D:\Python27\microblog\app\templates\index.html", line 5, in block "app_content"
    {{wtf.quick_form(form)}}
  File "d:\python27\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'wtf' is undefined
